name: macOS Workflow
on: [push]
jobs:
  test-macos:
    name: test on macOS
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install bmake
        run: brew install bmake
      - name: test
        run: sh -ex test.sh
